spring.application.name=practice

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=karthik
spring.datasource.password=Jackal@1202

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


